language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  matrix:
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
install:
  - pip install 'coverage<4' # coverage>=4 has issues with python3
  - pip install -q Django==$DJANGO_VERSION coveralls
  - python setup.py egg_info
script: coverage run --source='linaro_django_pagination' --omit *runner*,*test_project* setup.py test
after_success:
  - coveralls
